spring:
  application:
    name: mybatis-plus
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: taobang
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml