
server:
  context-path: /web

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: taobang
    #driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.laozhang.max_mybatis_mapper.bean
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE


#mappers 多个接口时逗号隔开
mapper:
  mappers: com.laozhang.max_mybatis_mapper.config.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    com:
      springboot:
        mapper: debug