server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abc
    password: abc
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
# Activiti7历史表创建
  activiti:
    history-level: full
    db-history-used: true
# 自动部署
    check-process-definitions: false
