zuul:
  routes:
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  sensitive-headers:
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/is-security?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: taobang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    
server:
  port: 9070     